name: localization_demo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # localizations
  intl: ^0.18.1
  intl_utils: ^2.8.5
  # logging and appenders
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
    

  # more opinionated lints than flutter lints
  lint: ^2.1.2
  # replaces DCM
  dart_code_linter: ^1.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# intl stuff via intl utils
flutter_intl:
  enabled: true
  class_name: CustomAppLocalizations
  main_locale: en
  arb_dir: lib/src/localization
  output_dir: lib/src/localization
