name: lint_demo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/images/android-icon-monochrome-raw.png"
  image_path_ios: "assets/images/ios_icon_1024x1024.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/background-raw.png" 
  adaptive_icon_foreground: "assets/images/foreground-raw.png" 
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/web_icon_1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/desktop_icon_1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/desktop_icon_1024x1024.png"



dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.1.2


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
